import Head from "next/head";

export default function Coachs() {
  return (
    <>
      <Head>
        <title>AppName - Coach list</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex container max-w-7xl flex-col  items-center mx-auto">
        <h1>Coachs</h1>
        <section className="py-10 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4">
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
          <div className="w-64 h-80 bg-slate-300">card</div>
        </section>
      </div>
    </>
  );
}
