import Head from "next/head";


export default function Profile() {
    return (
      <>
        <Head>
          <title>AppName - Coach profile</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <div>
          <h1>Coach profile page</h1>
        </div>
      </>
    );
  }
  