import Head from "next/head";

export default function Register() {
  return (
    <>
      <Head>
        <title>AppName - Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-center">
        {/* eslint-disable-next-line react/no-unescaped-entities */}
        <h1>S'enregistrer</h1>
      </div>
    </>
  );
}
